// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface;
using SevenZip.NativeInterface.Compression;
using SevenZip.NativeWrapper.Managed.linux.x86.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.linux.x86.Compression
{
    class CompressSetCoderProperties
        : Unknown, ICompressSetCoderProperties
    {
        protected CompressSetCoderProperties(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        public static ICompressSetCoderProperties Create(IntPtr nativeInterfaceObject)
        {
            if (nativeInterfaceObject == IntPtr.Zero)
                throw new ArgumentNullException(nameof(nativeInterfaceObject));

            return new CompressSetCoderProperties(nativeInterfaceObject);
        }

        void ICompressSetCoderProperties.SetCoderProperties(ICoderProperties propertiesGetter)
        {
            if (propertiesGetter is null)
                throw new ArgumentNullException(nameof(propertiesGetter));

            var result = UnmanagedEntryPoint.ICompressSetCoderProperties__SetCoderProperties(NativeInterfaceObject, propertiesGetter.EnumerateProperties());
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
        }
    }
}
