// This file is automatically generated. Do not rewrite manually.

using System;
using System.Runtime.InteropServices;

namespace SevenZip.NativeWrapper.Managed.macOs.x64
{

#if _PLATFORM_X64 || _PLATFORM_ARM64
    [StructLayout(LayoutKind.Explicit, Pack = 8, Size = 24)]
    unsafe struct PROPVARIANT
    {
        [FieldOffset(0)]
        public PropertyValueType ValueType;

        [FieldOffset(8)]
        public PROPVARIANT_BOOLEAN_VALUE BooleanValue;

        [FieldOffset(8)]
        public UInt32 UInt32Value;

        [FieldOffset(8)]
        public UInt64 UInt64Value;

        [FieldOffset(8)]
        public Char* StringValue;

        [FieldOffset(8)]
        public NativeFILETIME FileTimeValue;

        public static unsafe void Clear(PROPVARIANT* propertyValue)
        {
            UInt64* ptr = (UInt64*)propertyValue;
            *ptr++ = 0;
            *ptr = 0;
        }

        public static void Clear(ref PROPVARIANT propertyValue)
        {
            unsafe
            {
                fixed (PROPVARIANT* propertyValuePtr = &propertyValue)
                {
                    Clear(propertyValuePtr);
                }
            }
        }
    }
#elif _PLATFORM_X86 || _PLATFORM_ARM32
    [StructLayout(LayoutKind.Explicit, Pack = 4, Size = 16)]
    unsafe struct PROPVARIANT
    {
        [FieldOffset(0)]
        public PropertyValueType ValueType;

        [FieldOffset(8)]
        public PROPVARIANT_BOOLEAN_VALUE BooleanValue;

        [FieldOffset(8)]
        public UInt32 UInt32Value;

        [FieldOffset(8)]
        public UInt64 UInt64Value;

        [FieldOffset(8)]
        public Char* StringValue;

        [FieldOffset(8)]
        public NativeFILETIME FileTimeValue;

        public static unsafe void Clear(PROPVARIANT* propertyValue)
        {
            UInt32* ptr = (UInt32*)propertyValue;
            *ptr++ = 0;
            *ptr++ = 0;
            *ptr++ = 0;
            *ptr = 0;
        }

        public static void Clear(ref PROPVARIANT propertyValue)
        {
            unsafe
            {
                fixed (PROPVARIANT* propertyValuePtr = &propertyValue)
                {
                    Clear(propertyValuePtr);
                }
            }
        }
    }
#else
#error Not supported platform
#endif
}
