// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface;
using SevenZip.NativeInterface.Compression;
using SevenZip.NativeWrapper.Managed.macOs.arm64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.macOs.arm64.Compression
{
    class CompressCodecInfo
        : ICompressCodecInfo, IDisposable
    {
        private static readonly object _lockObject;

        // [Note]
        //  When calling ICompressCodecsInfo__GetProperty, if the PROPVARIANT structure returns the VT_BSTR type,
        // the PROPVARIANT structure is set to a pointer to the memory acquired inside 7-zip.
        //  There is no way to free this memory from the caller.
        //  However, by calling ICompressCodecsInfo__GetProperty again using the same PROPVARIANT structure,
        // 7-zip will release the memory pointed to by the pointer already set before setting the new value in the PROPVARIANT structure.
        //  Due to this property, the PROPVARIANT structure used in ICompressCodecsInfo__GetProperty should be shared as much as possible.
        //  Also, for the same reason, the PROPVARIANT structure must first be initialized to zero.
        //  And if possible, you should first call CompressCodecsInfo__GetProperty, which returns the VT_BSTR type.
        private static PROPVARIANT _propertyValueBuffer;
        private static NativeGUID _compressCoderInterfaceId;
        private static NativeGUID _compressCoder2InterfaceId;
        private static NativeGUID _compressFilterInterfaceId;

        private IntPtr _compressCodecsInfo;
        private bool _isDisposed;

        static CompressCodecInfo()
        {
            _lockObject = new object();
            PROPVARIANT.Clear(ref _propertyValueBuffer);
            NativeGUID.CopyFromManagedGuidToNativeGuid(typeof(ICompressCoder).GUID, ref _compressCoderInterfaceId);
            NativeGUID.CopyFromManagedGuidToNativeGuid(typeof(ICompressCoder2).GUID, ref _compressCoder2InterfaceId);
            NativeGUID.CopyFromManagedGuidToNativeGuid(typeof(ICompressFilter).GUID, ref _compressFilterInterfaceId);
        }

        private CompressCodecInfo(IntPtr compressCodecsInfo, Int32 index, UInt64 id, string codecName, Guid coderClassId, UInt32 packStreams, bool isFilter, CoderType coderType, bool isSupportedICompressCoder, bool isSupportedICompressCoder2, bool isSupportedICompressFilter)
        {
            _isDisposed = false;
            _compressCodecsInfo = compressCodecsInfo;
            Index = index;
            ID = id;
            CodecName = codecName;
            CoderClassId = coderClassId;
            PackStreams = packStreams;
            IsFilter = isFilter;
            CoderType = coderType;
            IsSupportedICompressCoder = isSupportedICompressCoder;
            IsSupportedICompressCoder2 = isSupportedICompressCoder2;
            IsSupportedICompressFilter = isSupportedICompressFilter;
        }

        ~CompressCodecInfo()
        {
            Dispose(disposing: false);
        }

        public Int32 Index { get; }

        public UInt64 ID { get; }

        public string CodecName { get; }

        public Guid CoderClassId { get; }

        public UInt32 PackStreams { get; }

        public bool IsFilter { get; }

        public CoderType CoderType { get; }

        public bool IsSupportedICompressCoder { get; }

        public bool IsSupportedICompressCoder2 { get; }

        public bool IsSupportedICompressFilter { get; }

        public static ICompressCodecInfo? Create(IntPtr compressCodecsInfo, Int32 index, CoderType coderType)
        {
            if (compressCodecsInfo == IntPtr.Zero)
                throw new ArgumentNullException(nameof(compressCodecsInfo));

            lock (_lockObject)
            {
                var ifp = compressCodecsInfo;
                var codecName = GetCodecName(ifp, index, ref _propertyValueBuffer);
                var packStreams = GetPackStreams(ifp, index, ref _propertyValueBuffer);
                var isFilter = GetIsFilter(ifp, index, ref _propertyValueBuffer);
                switch (coderType)
                {
                    case CoderType.Decoder:
                        if (GetIsDecoderAssigned(ifp, index, ref _propertyValueBuffer))
                        {
                            var coderClassId = GetDecoderClassId(ifp, index, ref _propertyValueBuffer);
                            var codecId = GetCodecId(ifp, index, ref _propertyValueBuffer);
                            IntPtr compressCoder = IntPtr.Zero;
                            IntPtr compressCoder2 = IntPtr.Zero;
                            IntPtr compressFilter = IntPtr.Zero;
                            try
                            {
                                compressCoder = CreateCompressDecoder(ifp, index, ref _compressCoderInterfaceId);
                                compressCoder2 = CreateCompressDecoder(ifp, index, ref _compressCoder2InterfaceId);
                                compressFilter = CreateCompressDecoder(ifp, index, ref _compressFilterInterfaceId);
                                _ = UnmanagedEntryPoint.IUnknown__AddRef(ifp);
                                return new CompressCodecInfo(
                                    ifp,
                                    index,
                                    codecId,
                                    codecName,
                                    coderClassId,
                                    packStreams,
                                    isFilter,
                                    coderType,
                                    compressCoder != IntPtr.Zero,
                                    compressCoder2 != IntPtr.Zero,
                                    compressFilter != IntPtr.Zero);
                            }
                            finally
                            {
                                if (compressFilter != IntPtr.Zero)
                                    _ = UnmanagedEntryPoint.IUnknown__Release(compressFilter);
                                if (compressCoder2 != IntPtr.Zero)
                                    _ = UnmanagedEntryPoint.IUnknown__Release(compressCoder2);
                                if (compressCoder != IntPtr.Zero)
                                    _ = UnmanagedEntryPoint.IUnknown__Release(compressCoder);
                            }
                        }
                        else
                            return null;
                    case CoderType.Encoder:
                        if (GetIsEncoderAssigned(ifp, index, ref _propertyValueBuffer))
                        {
                            var coderClassId = GetEncoderClassId(ifp, index, ref _propertyValueBuffer);
                            var codecId = GetCodecId(ifp, index, ref _propertyValueBuffer);
                            IntPtr compressCoder = IntPtr.Zero;
                            IntPtr compressCoder2 = IntPtr.Zero;
                            IntPtr compressFilter = IntPtr.Zero;
                            try
                            {
                                compressCoder = CreateCompressEncoder(ifp, index, ref _compressCoderInterfaceId);
                                compressCoder2 = CreateCompressEncoder(ifp, index, ref _compressCoder2InterfaceId);
                                compressFilter = CreateCompressEncoder(ifp, index, ref _compressFilterInterfaceId);
                                _ = UnmanagedEntryPoint.IUnknown__AddRef(ifp);
                                return new CompressCodecInfo(
                                    ifp,
                                    index,
                                    codecId,
                                    codecName,
                                    coderClassId,
                                    packStreams,
                                    isFilter,
                                    coderType,
                                    compressCoder != IntPtr.Zero,
                                    compressCoder2 != IntPtr.Zero,
                                    compressFilter != IntPtr.Zero);
                            }
                            finally
                            {
                                if (compressFilter != IntPtr.Zero)
                                    _ = UnmanagedEntryPoint.IUnknown__Release(compressFilter);
                                if (compressCoder2 != IntPtr.Zero)
                                    _ = UnmanagedEntryPoint.IUnknown__Release(compressCoder2);
                                if (compressCoder != IntPtr.Zero)
                                    _ = UnmanagedEntryPoint.IUnknown__Release(compressCoder);
                            }
                        }
                        else
                            return null;
                    default:
                        return null;
                }
            }
        }

        ICompressCoder ICompressCodecInfo.CreateCompressCoder()
        {
            if (!IsSupportedICompressCoder)
                throw new NotSupportedException();

            return
                CompressCoder.Create(
                    CoderType switch
                    {
                        CoderType.Decoder => CreateCompressDecoder(_compressCodecsInfo, Index, ref _compressCoderInterfaceId),
                        CoderType.Encoder => CreateCompressEncoder(_compressCodecsInfo, Index, ref _compressCoderInterfaceId),
                        _ => throw new Exception($"Unknown coder type: {CoderType}"),
                    });
        }

        ICompressCoder2 ICompressCodecInfo.CreateCompressCoder2()
        {
            if (!IsSupportedICompressCoder2)
                throw new NotSupportedException();

            return
                CompressCoder2.Create(
                    CoderType switch
                    {
                        CoderType.Decoder => CreateCompressDecoder(_compressCodecsInfo, Index, ref _compressCoder2InterfaceId),
                        CoderType.Encoder => CreateCompressEncoder(_compressCodecsInfo, Index, ref _compressCoder2InterfaceId),
                        _ => throw new Exception($"Unknown coder type: {CoderType}"),
                    });
        }

        public ICompressFilter CreateCompressFilter()
        {
            if (!IsSupportedICompressFilter)
                throw new NotSupportedException();

            return
                CompressFilter.Create(
                    CoderType switch
                    {
                        CoderType.Decoder => CreateCompressDecoder(_compressCodecsInfo, Index, ref _compressFilterInterfaceId),
                        CoderType.Encoder => CreateCompressEncoder(_compressCodecsInfo, Index, ref _compressFilterInterfaceId),
                        _ => throw new Exception($"Unknown coder type: {CoderType}"),
                    });
        }

        public void Dispose()
        {
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!_isDisposed)
            {
                if (disposing)
                {
                }
                if (_compressCodecsInfo != IntPtr.Zero)
                {
                    UnmanagedEntryPoint.ICompressSetInStream__ReleaseInStream(_compressCodecsInfo);
                    _compressCodecsInfo = IntPtr.Zero;
                }
                _isDisposed = true;
            }
        }

        private static UInt64 GetCodecId(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.ID, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            if (valueBuffer.ValueType != PropertyValueType.VT_UI8)
                throw new Exception("Unexpected value type.");
            return valueBuffer.UInt64Value;
        }

        private static string GetCodecName(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.Name, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            if (valueBuffer.ValueType != PropertyValueType.VT_BSTR)
                throw new Exception("Unexpected value type.");
            unsafe
            {
                return new string(valueBuffer.StringValue);
            }
        }

        private static bool GetIsDecoderAssigned(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.DecoderIsAssigned, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            if (valueBuffer.ValueType != PropertyValueType.VT_BOOL)
                throw new Exception("Unexpected value type.");
            return valueBuffer.BooleanValue != PROPVARIANT_BOOLEAN_VALUE.FALSE;
        }

        private static bool GetIsEncoderAssigned(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.EncoderIsAssigned, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            if (valueBuffer.ValueType != PropertyValueType.VT_BOOL)
                throw new Exception("Unexpected value type.");
            return valueBuffer.BooleanValue != PROPVARIANT_BOOLEAN_VALUE.FALSE;
        }

        private static Guid GetDecoderClassId(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.Decoder, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            if (valueBuffer.ValueType != PropertyValueType.VT_BSTR)
                throw new Exception("Unexpected value type.");
            unsafe
            {
                return new Guid(new ReadOnlySpan<Byte>(valueBuffer.StringValue, sizeof(NativeGUID)));
            }
        }

        private static Guid GetEncoderClassId(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.Encoder, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            if (valueBuffer.ValueType != PropertyValueType.VT_BSTR)
                throw new Exception("Unexpected value type.");
            unsafe
            {
                return new Guid(new ReadOnlySpan<Byte>(valueBuffer.StringValue, sizeof(NativeGUID)));
            }
        }

        private static IntPtr CreateCompressDecoder(IntPtr ifp, Int32 index, ref NativeGUID interfaceId)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__CreateDecoder(ifp, (UInt32)index, ref interfaceId, out IntPtr coder);
            if (result == HRESULT.S_OK)
                return coder;
            else if (result == HRESULT.E_NOINTERFACE)
                return IntPtr.Zero;
            else
                throw result.GetExceptionFromHRESULT();
        }

        private static IntPtr CreateCompressEncoder(IntPtr ifp, Int32 index, ref NativeGUID interfaceId)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__CreateEncoder(ifp, (UInt32)index, ref interfaceId, out IntPtr coder);
            if (result == HRESULT.S_OK)
                return coder;
            else if (result == HRESULT.E_NOINTERFACE)
                return IntPtr.Zero;
            else
                throw result.GetExceptionFromHRESULT();
        }

        private static UInt32 GetPackStreams(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.PackStreams, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            return
                valueBuffer.ValueType switch
                {
                    PropertyValueType.VT_EMPTY => 1,
                    PropertyValueType.VT_UI4 => valueBuffer.UInt32Value,
                    _ => throw new Exception("Unexpected value type."),
                };
        }

        private static bool GetIsFilter(IntPtr ifp, Int32 index, ref PROPVARIANT valueBuffer)
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetProperty(ifp, (UInt32)index, MethodPropID.IsFilter, ref valueBuffer);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            if (valueBuffer.ValueType != PropertyValueType.VT_BOOL)
                throw new Exception("Unexpected value type.");
            return valueBuffer.BooleanValue != PROPVARIANT_BOOLEAN_VALUE.FALSE;
        }
    }
}
