// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface.Compression;
using SevenZip.NativeInterface.IO;
using SevenZip.NativeWrapper.Managed.macOs.arm64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.macOs.arm64.Compression
{
    class CompressCoder2
        : Unknown, ICompressCoder2
    {
        protected CompressCoder2(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        public static ICompressCoder2 Create(IntPtr nativeInterfaceObject)
        {
            if (nativeInterfaceObject == IntPtr.Zero)
                throw new ArgumentNullException(nameof(nativeInterfaceObject));

            return new CompressCoder2(nativeInterfaceObject);
        }

        void ICompressCoder2.Code(ReadOnlySpan<(SequentialInStreamReader sequentialInStreamReader, UInt64? inStreamSize)> inStreams, ReadOnlySpan<(SequentialOutStreamWriter sequentialOutStreamWriter, UInt64? outStreamSize)> outStreams, CompressProgressInfoReporter? progressReporter)
        {
            var result =
                UnmanagedEntryPoint.ICompressCoder2__Code(
                    NativeInterfaceObject,
                    inStreams,
                    outStreams,
                    progressReporter);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
        }
    }
}
