// This file is automatically generated. Do not rewrite manually.

using System;

namespace SevenZip.NativeWrapper.Managed.win.arm64
{
    enum HRESULT
        : Int32
    {
        S_OK = 0,
        E_NOINTERFACE = unchecked((Int32)0x80004002),
        E_DLL_NOT_FOUND = unchecked((Int32)0x8007007e),
    }
}
