// This file is automatically generated. Do not rewrite manually.

using System;

namespace SevenZip.NativeWrapper.Managed.win.arm64
{
    delegate HRESULT NativeInStreamReader(IntPtr buffer, UInt32 size, out UInt32 processedSize);
}
