// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface.Compression;
using SevenZip.NativeWrapper.Managed.linux.x64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.linux.x64.Compression
{
    class CompressGetInStreamProcessedSize
        : Unknown, ICompressGetInStreamProcessedSize
    {
        protected CompressGetInStreamProcessedSize(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        UInt64 ICompressGetInStreamProcessedSize.InStreamProcessedSize
        {
            get
            {
                var result = UnmanagedEntryPoint.ICompressGetInStreamProcessedSize__GetInStreamProcessedSize(NativeInterfaceObject, out UInt64 processedSize);
                if (result != HRESULT.S_OK)
                    throw result.GetExceptionFromHRESULT();
                return processedSize;
            }
        }

        public static ICompressGetInStreamProcessedSize Create(IntPtr nativeInterfaceObject)
        {
            if (nativeInterfaceObject == IntPtr.Zero)
                throw new ArgumentNullException(nameof(nativeInterfaceObject));

            return new CompressGetInStreamProcessedSize(nativeInterfaceObject);
        }
    }
}
