// This file is automatically generated. Do not rewrite manually.

using System;

namespace SevenZip.NativeWrapper.Managed.macOs.arm64
{
    delegate HRESULT NativeOutStraamWriter(IntPtr buffer, UInt32 size, out UInt32 processedSize);
}
