// This file is automatically generated. Do not rewrite manually.

using System;

namespace SevenZip.NativeWrapper.Managed.macOs.arm64
{
    enum PROPVARIANT_BOOLEAN_VALUE
        : UInt16
    {
        FALSE = 0,
        TRUE = 0xffff,
    }
}
