// This file is automatically generated. Do not rewrite manually.

using System;
using System.Runtime.InteropServices;

namespace SevenZip.Compression.NativeInterfaces
{
    [Guid("23170f69-40c1-278a-0000-000400220000")]
    internal sealed partial class CompressSetDecoderProperties2
         : Unknown
    {
        private CompressSetDecoderProperties2(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }
    }
}
