// This file is automatically generated. Do not rewrite manually.

using System;
using System.Runtime.InteropServices;

namespace SevenZip.Compression.NativeInterfaces
{
    [Guid("23170f69-40c1-278a-0000-0004001f0000")]
    internal sealed partial class CompressSetCoderPropertiesOpt
         : Unknown
    {
        private CompressSetCoderPropertiesOpt(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }
    }
}
