// This file is automatically generated. Do not rewrite manually.

using System;
using System.Linq;
using System.Runtime.InteropServices;

namespace SevenZip.Compression.NativeInterfaces
{
    [Guid("00000000-0000-0000-c000-000000000046")]
    partial class Unknown
    {
        private static readonly (Guid iid, Func<IntPtr, Unknown> instanceCreator)[] _instanceCreators = new []
            {
                (iid: new Guid("23170f69-40c1-278a-0000-000300010000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => SequentialInStream.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400050000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressCoder.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-0004001f0000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetCoderPropertiesOpt.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400200000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetCoderProperties.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400220000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetDecoderProperties2.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400230000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressWriteCoderProperties.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400240000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressGetInStreamProcessedSize.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400250000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetCoderMt.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400260000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetFinishMode.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400280000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetMemLimit.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400290000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressReadUnusedFromInBuf.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400310000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetInStream.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400340000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetOutStreamSize.Create(nativeInterfaceObject))),
                (iid: new Guid("23170f69-40c1-278a-0000-000400350000"), instanceCreator: (Func<IntPtr, Unknown>)(nativeInterfaceObject => CompressSetBufSize.Create(nativeInterfaceObject))),
            }
            .OrderBy(item => item.iid)
            .ToArray();
    }
}
