// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface.IO;
using SevenZip.NativeWrapper.Managed.linux.arm64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.linux.arm64.IO
{
    class SequentialInStream
        : Unknown, ISequentialInStream
    {
        protected SequentialInStream(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        public static ISequentialInStream Create(IntPtr nativeInterfaceObject)
        {
            return new SequentialInStream(nativeInterfaceObject);
        }

        UInt32 ISequentialInStream.Read(Span<Byte> buffer)
        {
            var result = UnmanagedEntryPoint.ISequentialInStream__Read(NativeInterfaceObject, buffer, out UInt32 processedSize);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            return processedSize;
        }
    }
}
