// This file is automatically generated. Do not rewrite manually.

using System;

namespace SevenZip.NativeWrapper.Managed.win.x64
{
    delegate void NativeProgressReporter(IntPtr inSize, IntPtr outSize);
}
