// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface;
using SevenZip.NativeInterface.Compression;
using SevenZip.NativeWrapper.Managed.macOs.x64.Platform;
using System;
using System.Collections.Generic;
using System.IO;

namespace SevenZip.NativeWrapper.Managed.macOs.x64.Compression
{
    /// <summary>
    /// A class of set of codecs.
    /// </summary>
    public class CompressCodecsInfo
        : Unknown, ICompressCodecsInfo
    {
        /// <summary>
        /// The default constructor.
        /// </summary>
        public CompressCodecsInfo()
            : base(IntPtr.Zero)
        {
        }

        bool ICompressCodecsInfo.Initialize(string seevenZipNativeLibraryPath)
        {
            if (string.IsNullOrEmpty(seevenZipNativeLibraryPath))
                throw new ArgumentException($"'{nameof(seevenZipNativeLibraryPath)}' を NULL または空にすることはできません。", nameof(seevenZipNativeLibraryPath));

            var result = UnmanagedEntryPoint.ICompressCodecsInfo_Create(seevenZipNativeLibraryPath, out IntPtr nativeResource);
            if (result != HRESULT.S_OK)
            {
                if (result != HRESULT.E_DLL_NOT_FOUND)
                    throw result.GetExceptionFromHRESULT();
                return false;
            }
            AttatchNativeInterfaceObject(nativeResource);
            return true;
        }

        IEnumerable<ICompressCodecInfo> ICompressCodecsInfo.EnumerateCodecs()
        {
            var codecsCount = GetNumMethods();
            for (var index = 0; index < codecsCount; ++index)
            {
                var decoder = CompressCodecInfo.Create(NativeInterfaceObject, index, CoderType.Decoder);
                if (decoder is not null)
                    yield return decoder;
                var encoder = CompressCodecInfo.Create(NativeInterfaceObject, index, CoderType.Encoder);
                if (encoder is not null)
                    yield return encoder;
            }
        }

        IUnknown IUnknown.QueryInterface(Type interfaceType)
        {
            if (interfaceType is null)
                throw new ArgumentNullException(nameof(interfaceType));

            if (interfaceType.GUID == typeof(IUnknown).GUID)
                return this;
            else if (interfaceType.GUID == typeof(ICompressCodecsInfo).GUID)
                return this;
            else
                throw new NotSupportedException();
        }

        private UInt32 GetNumMethods()
        {
            var result = UnmanagedEntryPoint.ICompressCodecsInfo__GetNumMethods(NativeInterfaceObject, out UInt32 count);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            return count;
        }
    }
}
