// This file is automatically generated. Do not rewrite manually.

using System;

namespace SevenZip.NativeWrapper.Managed.macOs.x86
{
    enum MethodPropID
        : UInt32
    {
        ID,
        Name,
        Decoder,
        Encoder,
        PackStreams,
        UnpackStreams,
        Description,
        DecoderIsAssigned,
        EncoderIsAssigned,
        DigestSize,
        IsFilter
    }
}
