// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface.Compression;
using SevenZip.NativeInterface.IO;
using SevenZip.NativeWrapper.Managed.win.arm64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.win.arm64.Compression
{
    class CompressWriteCoderProperties
        : Unknown, ICompressWriteCoderProperties
    {
        protected CompressWriteCoderProperties(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        public static ICompressWriteCoderProperties Create(IntPtr nativeInterfaceObject)
        {
            if (nativeInterfaceObject == IntPtr.Zero)
                throw new ArgumentNullException(nameof(nativeInterfaceObject));

            return new CompressWriteCoderProperties(nativeInterfaceObject);
        }

        void ICompressWriteCoderProperties.WriteCoderProperties(SequentialOutStreamWriter outStreamWriter)
        {
            if (outStreamWriter is null)
                throw new ArgumentNullException(nameof(outStreamWriter));

            var result = UnmanagedEntryPoint.ICompressWriteCoderProperties__WriteCoderProperties(NativeInterfaceObject, outStreamWriter);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
        }
    }
}
