// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface.Compression;
using SevenZip.NativeWrapper.Managed.win.arm64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.win.arm64.Compression
{
    class CompressReadUnusedFromInBuf
        : Unknown, ICompressReadUnusedFromInBuf
    {
        protected CompressReadUnusedFromInBuf(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        public static ICompressReadUnusedFromInBuf Create(IntPtr nativeInterfaceObject)
        {
            if (nativeInterfaceObject == IntPtr.Zero)
                throw new ArgumentNullException(nameof(nativeInterfaceObject));

            return new CompressReadUnusedFromInBuf(nativeInterfaceObject);
        }

        UInt32 ICompressReadUnusedFromInBuf.ReadUnusedFromInBuf(Span<Byte> data)
        {
            var result = UnmanagedEntryPoint.ICompressReadUnusedFromInBuf__ReadUnusedFromInBuf(NativeInterfaceObject, data, out UInt32 processedSize);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
            return processedSize;
        }
    }
}
