// This file is automatically generated. Do not rewrite manually.

#include "InterfaceDefinitions.h"
#include "Guid.h"
#include "SevenZipInterface.h"

#include "ManagedUnknown.h"
#include "ManagedSequentialInStream.h"
// #include "ManagedSequentialOutStream.h"
// #include "ManagedInStream.h"
// #include "ManagedOutStream.h"
// #include "ManagedStreamGetSize.h"
// #include "ManagedOutStreamFinish.h"
// #include "ManagedStreamGetProps.h"
// #include "ManagedStreamGetProps2.h"
// #include "ManagedCompressProgressInfo.h"
#include "ManagedCompressCoder.h"
#include "ManagedCompressCoder2.h"
#include "ManagedCompressSetCoderPropertiesOpt.h"
#include "ManagedCompressSetCoderProperties.h"
#include "ManagedCompressSetDecoderProperties2.h"
#include "ManagedCompressWriteCoderProperties.h"
#include "ManagedCompressGetInStreamProcessedSize.h"
#include "ManagedCompressSetCoderMt.h"
#include "ManagedCompressSetFinishMode.h"
// #include "ManagedCompressGetInStreamProcessedSize2.h"
#include "ManagedCompressSetMemLimit.h"
#include "ManagedCompressReadUnusedFromInBuf.h"
// #include "ManagedCompressGetSubStreamSize.h"
#include "ManagedCompressSetInStream.h"
// #include "ManagedCompressSetOutStream.h"
#include "ManagedCompressSetOutStreamSize.h"
#include "ManagedCompressSetBufSize.h"
// #include "ManagedCompressInitEncoder.h"
// #include "ManagedCompressSetInStream2.h"
#include "ManagedCompressFilter.h"
#include "ManagedCompressCodecsInfo.h"
// #include "ManagedSetCompressCodecsInfo.h"
// #include "ManagedCryptoProperties.h"
// #include "ManagedCryptoResetInitVector.h"
// #include "ManagedCryptoSetPassword.h"
// #include "ManagedCryptoSetCRC.h"
// #include "ManagedHasher.h"
// #include "ManagedHashers.h"

#ifndef ENABLE_MSVC_SPECIFIC_SPECIFICATIONS
GUID IID_IUnknown = { 0x00000000, 0x0000, 0x0000, { 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46 }}
GUID IID_ISequentialInStream = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x00, 0x00 }}
GUID IID_ISequentialOutStream = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x02, 0x00, 0x00 }}
GUID IID_IInStream = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x03, 0x00, 0x00 }}
GUID IID_IOutStream = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x04, 0x00, 0x00 }}
GUID IID_IStreamGetSize = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x06, 0x00, 0x00 }}
GUID IID_IOutStreamFinish = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x07, 0x00, 0x00 }}
GUID IID_IStreamGetProps = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x08, 0x00, 0x00 }}
GUID IID_IStreamGetProps2 = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x03, 0x00, 0x09, 0x00, 0x00 }}
GUID IID_ICompressProgressInfo = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00 }}
GUID IID_ICompressCoder = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x05, 0x00, 0x00 }}
GUID IID_ICompressCoder2 = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x18, 0x00, 0x00 }}
GUID IID_ICompressSetCoderPropertiesOpt = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x1f, 0x00, 0x00 }}
GUID IID_ICompressSetCoderProperties = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x20, 0x00, 0x00 }}
GUID IID_ICompressSetDecoderProperties2 = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x22, 0x00, 0x00 }}
GUID IID_ICompressWriteCoderProperties = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x23, 0x00, 0x00 }}
GUID IID_ICompressGetInStreamProcessedSize = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x24, 0x00, 0x00 }}
GUID IID_ICompressSetCoderMt = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x25, 0x00, 0x00 }}
GUID IID_ICompressSetFinishMode = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x26, 0x00, 0x00 }}
GUID IID_ICompressGetInStreamProcessedSize2 = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x27, 0x00, 0x00 }}
GUID IID_ICompressSetMemLimit = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x28, 0x00, 0x00 }}
GUID IID_ICompressReadUnusedFromInBuf = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x29, 0x00, 0x00 }}
GUID IID_ICompressGetSubStreamSize = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x30, 0x00, 0x00 }}
GUID IID_ICompressSetInStream = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x31, 0x00, 0x00 }}
GUID IID_ICompressSetOutStream = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x32, 0x00, 0x00 }}
GUID IID_ICompressSetOutStreamSize = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x34, 0x00, 0x00 }}
GUID IID_ICompressSetBufSize = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x35, 0x00, 0x00 }}
GUID IID_ICompressInitEncoder = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x36, 0x00, 0x00 }}
GUID IID_ICompressSetInStream2 = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x37, 0x00, 0x00 }}
GUID IID_ICompressFilter = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x40, 0x00, 0x00 }}
GUID IID_ICompressCodecsInfo = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x60, 0x00, 0x00 }}
GUID IID_ISetCompressCodecsInfo = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x61, 0x00, 0x00 }}
GUID IID_ICryptoProperties = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x80, 0x00, 0x00 }}
GUID IID_ICryptoResetInitVector = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x8c, 0x00, 0x00 }}
GUID IID_ICryptoSetPassword = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0x90, 0x00, 0x00 }}
GUID IID_ICryptoSetCRC = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0xa0, 0x00, 0x00 }}
GUID IID_IHasher = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0xc0, 0x00, 0x00 }}
GUID IID_IHashers = { 0x23170f69, 0x40c1, 0x278a, { 0x00, 0x00, 0x00, 0x04, 0x00, 0xc1, 0x00, 0x00 }}
#endif  // ENABLE_MSVC_SPECIFIC_SPECIFICATIONS

using namespace SevenZip::NativeWrapper::IO;
using namespace SevenZip::NativeWrapper::Compression;

namespace SevenZip
{
    namespace NativeWrapper
    {
        SevenZip::NativeInterface::IUnknown^ CreateManagedInterfaceObject(const GUID& interfaceId, IUnknown* nativeUnknownObject)
        {
#if defined(_ARCHITECTURE_NATIVE_INTEGER_32_BIT)
            UInt32 guid0 = ((const UInt32*)&interfaceId)[0];
            UInt32 guid1 = ((const UInt32*)&interfaceId)[1];
            UInt32 guid2 = ((const UInt32*)&interfaceId)[2];
            UInt32 guid3 = ((const UInt32*)&interfaceId)[3];
#if defined(_ARCHITECTURE_LITTLE_ENDIAN)
                if (guid0 != 0x23170f69)
                    return nullptr;
                if (guid1 != 0x278a40c1)
                    return nullptr;
                if (guid2 == 0x03000000)
                {
                    if (guid3 != 0x00000100)
                        return nullptr;
                    return ManagedSequentialInStream::Create(nativeUnknownObject);
                }
                else if (guid2 == 0x04000000)
                {
                    if (guid3 < 0x00002500)
                    {
                        if (guid3 < 0x00002000)
                        {
                            if (guid3 < 0x00001800)
                            {
                                if (guid3 != 0x00000500)
                                    return nullptr;
                                return ManagedCompressCoder::Create(nativeUnknownObject);
                            }
                            else
                            {
                                if (guid3 == 0x00001800)
                                    return ManagedCompressCoder2::Create(nativeUnknownObject);
                                else if (guid3 == 0x00001f00)
                                    return ManagedCompressSetCoderPropertiesOpt::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00002300)
                            {
                                if (guid3 == 0x00002000)
                                    return ManagedCompressSetCoderProperties::Create(nativeUnknownObject);
                                else if (guid3 == 0x00002200)
                                    return ManagedCompressSetDecoderProperties2::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                            else
                            {
                                if (guid3 == 0x00002300)
                                    return ManagedCompressWriteCoderProperties::Create(nativeUnknownObject);
                                else if (guid3 == 0x00002400)
                                    return ManagedCompressGetInStreamProcessedSize::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                    }
                    else
                    {
                        if (guid3 < 0x00003100)
                        {
                            if (guid3 < 0x00002800)
                            {
                                if (guid3 == 0x00002500)
                                    return ManagedCompressSetCoderMt::Create(nativeUnknownObject);
                                else if (guid3 == 0x00002600)
                                    return ManagedCompressSetFinishMode::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                            else
                            {
                                if (guid3 == 0x00002800)
                                    return ManagedCompressSetMemLimit::Create(nativeUnknownObject);
                                else if (guid3 == 0x00002900)
                                    return ManagedCompressReadUnusedFromInBuf::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00003500)
                            {
                                if (guid3 == 0x00003100)
                                    return ManagedCompressSetInStream::Create(nativeUnknownObject);
                                else if (guid3 == 0x00003400)
                                    return ManagedCompressSetOutStreamSize::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                            else
                            {
                                if (guid3 == 0x00003500)
                                    return ManagedCompressSetBufSize::Create(nativeUnknownObject);
                                else if (guid3 == 0x00004000)
                                    return ManagedCompressFilter::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                    }
                }
                else
                    return nullptr;
#elif defined(_ARCHITECTURE_BIG_ENDIAN)
                if (guid0 != 0x690f1723)
                    return nullptr;
                if (guid1 != 0xc1408a27)
                    return nullptr;
                if (guid2 == 0x00000003)
                {
                    if (guid3 != 0x00010000)
                        return nullptr;
                    return ManagedSequentialInStream::Create(nativeUnknownObject);
                }
                else if (guid2 == 0x00000004)
                {
                    if (guid3 < 0x00250000)
                    {
                        if (guid3 < 0x00200000)
                        {
                            if (guid3 < 0x00180000)
                            {
                                if (guid3 != 0x00050000)
                                    return nullptr;
                                return ManagedCompressCoder::Create(nativeUnknownObject);
                            }
                            else
                            {
                                if (guid3 == 0x00180000)
                                    return ManagedCompressCoder2::Create(nativeUnknownObject);
                                else if (guid3 == 0x001f0000)
                                    return ManagedCompressSetCoderPropertiesOpt::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00230000)
                            {
                                if (guid3 == 0x00200000)
                                    return ManagedCompressSetCoderProperties::Create(nativeUnknownObject);
                                else if (guid3 == 0x00220000)
                                    return ManagedCompressSetDecoderProperties2::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                            else
                            {
                                if (guid3 == 0x00230000)
                                    return ManagedCompressWriteCoderProperties::Create(nativeUnknownObject);
                                else if (guid3 == 0x00240000)
                                    return ManagedCompressGetInStreamProcessedSize::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                    }
                    else
                    {
                        if (guid3 < 0x00310000)
                        {
                            if (guid3 < 0x00280000)
                            {
                                if (guid3 == 0x00250000)
                                    return ManagedCompressSetCoderMt::Create(nativeUnknownObject);
                                else if (guid3 == 0x00260000)
                                    return ManagedCompressSetFinishMode::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                            else
                            {
                                if (guid3 == 0x00280000)
                                    return ManagedCompressSetMemLimit::Create(nativeUnknownObject);
                                else if (guid3 == 0x00290000)
                                    return ManagedCompressReadUnusedFromInBuf::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00350000)
                            {
                                if (guid3 == 0x00310000)
                                    return ManagedCompressSetInStream::Create(nativeUnknownObject);
                                else if (guid3 == 0x00340000)
                                    return ManagedCompressSetOutStreamSize::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                            else
                            {
                                if (guid3 == 0x00350000)
                                    return ManagedCompressSetBufSize::Create(nativeUnknownObject);
                                else if (guid3 == 0x00400000)
                                    return ManagedCompressFilter::Create(nativeUnknownObject);
                                else
                                    return nullptr;
                            }
                        }
                    }
                }
                else
                    return nullptr;
#else
#error "Undefined macro '_ARCHITECTURE_xxx_ENDIAN'"
#endif
#elif defined(_ARCHITECTURE_NATIVE_INTEGER_64_BIT)
            UInt64 guid0 = ((const UInt64*)&interfaceId)[0];
            UInt64 guid1 = ((const UInt64*)&interfaceId)[1];
#if defined(_ARCHITECTURE_LITTLE_ENDIAN)
                if (guid0 != 0x278a40c123170f69)
                    return nullptr;
                if (guid1 < 0x250004000000)
                {
                    if (guid1 < 0x200004000000)
                    {
                        if (guid1 < 0x180004000000)
                        {
                            if (guid1 == 0x10003000000)
                                return ManagedSequentialInStream::Create(nativeUnknownObject);
                            else if (guid1 == 0x50004000000)
                                return ManagedCompressCoder::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x180004000000)
                                return ManagedCompressCoder2::Create(nativeUnknownObject);
                            else if (guid1 == 0x1f0004000000)
                                return ManagedCompressSetCoderPropertiesOpt::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                    else
                    {
                        if (guid1 < 0x230004000000)
                        {
                            if (guid1 == 0x200004000000)
                                return ManagedCompressSetCoderProperties::Create(nativeUnknownObject);
                            else if (guid1 == 0x220004000000)
                                return ManagedCompressSetDecoderProperties2::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x230004000000)
                                return ManagedCompressWriteCoderProperties::Create(nativeUnknownObject);
                            else if (guid1 == 0x240004000000)
                                return ManagedCompressGetInStreamProcessedSize::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                }
                else
                {
                    if (guid1 < 0x310004000000)
                    {
                        if (guid1 < 0x280004000000)
                        {
                            if (guid1 == 0x250004000000)
                                return ManagedCompressSetCoderMt::Create(nativeUnknownObject);
                            else if (guid1 == 0x260004000000)
                                return ManagedCompressSetFinishMode::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x280004000000)
                                return ManagedCompressSetMemLimit::Create(nativeUnknownObject);
                            else if (guid1 == 0x290004000000)
                                return ManagedCompressReadUnusedFromInBuf::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                    else
                    {
                        if (guid1 < 0x350004000000)
                        {
                            if (guid1 == 0x310004000000)
                                return ManagedCompressSetInStream::Create(nativeUnknownObject);
                            else if (guid1 == 0x340004000000)
                                return ManagedCompressSetOutStreamSize::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x350004000000)
                                return ManagedCompressSetBufSize::Create(nativeUnknownObject);
                            else if (guid1 == 0x400004000000)
                                return ManagedCompressFilter::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                }
#elif defined(_ARCHITECTURE_BIG_ENDIAN)
                if (guid0 != 0x690f1723c1408a27)
                    return nullptr;
                if (guid1 < 0x400250000)
                {
                    if (guid1 < 0x400200000)
                    {
                        if (guid1 < 0x400180000)
                        {
                            if (guid1 == 0x300010000)
                                return ManagedSequentialInStream::Create(nativeUnknownObject);
                            else if (guid1 == 0x400050000)
                                return ManagedCompressCoder::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x400180000)
                                return ManagedCompressCoder2::Create(nativeUnknownObject);
                            else if (guid1 == 0x4001f0000)
                                return ManagedCompressSetCoderPropertiesOpt::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                    else
                    {
                        if (guid1 < 0x400230000)
                        {
                            if (guid1 == 0x400200000)
                                return ManagedCompressSetCoderProperties::Create(nativeUnknownObject);
                            else if (guid1 == 0x400220000)
                                return ManagedCompressSetDecoderProperties2::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x400230000)
                                return ManagedCompressWriteCoderProperties::Create(nativeUnknownObject);
                            else if (guid1 == 0x400240000)
                                return ManagedCompressGetInStreamProcessedSize::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                }
                else
                {
                    if (guid1 < 0x400310000)
                    {
                        if (guid1 < 0x400280000)
                        {
                            if (guid1 == 0x400250000)
                                return ManagedCompressSetCoderMt::Create(nativeUnknownObject);
                            else if (guid1 == 0x400260000)
                                return ManagedCompressSetFinishMode::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x400280000)
                                return ManagedCompressSetMemLimit::Create(nativeUnknownObject);
                            else if (guid1 == 0x400290000)
                                return ManagedCompressReadUnusedFromInBuf::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                    else
                    {
                        if (guid1 < 0x400350000)
                        {
                            if (guid1 == 0x400310000)
                                return ManagedCompressSetInStream::Create(nativeUnknownObject);
                            else if (guid1 == 0x400340000)
                                return ManagedCompressSetOutStreamSize::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                        else
                        {
                            if (guid1 == 0x400350000)
                                return ManagedCompressSetBufSize::Create(nativeUnknownObject);
                            else if (guid1 == 0x400400000)
                                return ManagedCompressFilter::Create(nativeUnknownObject);
                            else
                                return nullptr;
                        }
                    }
                }
#else
#error "Undefined macro '_ARCHITECTURE_xxx_ENDIAN'"
#endif
#else
#error "Undefined macro '_ARCHITECTURE_NATIVE_INTEGER_xx_BIT'"
#endif
        }

#ifdef _DEBUG
        static void ValidateInterfaceId(const GUID& interfaceId)
        {
#if defined(_ARCHITECTURE_NATIVE_INTEGER_32_BIT)
            UInt32 guid0 = ((const UInt32*)&interfaceId)[0];
            UInt32 guid1 = ((const UInt32*)&interfaceId)[1];
            UInt32 guid2 = ((const UInt32*)&interfaceId)[2];
            UInt32 guid3 = ((const UInt32*)&interfaceId)[3];
#if defined(_ARCHITECTURE_LITTLE_ENDIAN)
                if (guid0 != 0x23170f69)
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                if (guid1 != 0x278a40c1)
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                if (guid2 == 0x03000000)
                {
                    if (guid3 != 0x00000100)
                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                {
                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ISequentialInStream)))
                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                }
                }
                else if (guid2 == 0x04000000)
                {
                    if (guid3 < 0x00002500)
                    {
                        if (guid3 < 0x00002000)
                        {
                            if (guid3 < 0x00001800)
                            {
                                if (guid3 != 0x00000500)
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            }
                            else
                            {
                                if (guid3 == 0x00001800)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder2)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00001f00)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderPropertiesOpt)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00002300)
                            {
                                if (guid3 == 0x00002000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderProperties)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00002200)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetDecoderProperties2)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                            {
                                if (guid3 == 0x00002300)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressWriteCoderProperties)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00002400)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressGetInStreamProcessedSize)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                    }
                    else
                    {
                        if (guid3 < 0x00003100)
                        {
                            if (guid3 < 0x00002800)
                            {
                                if (guid3 == 0x00002500)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderMt)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00002600)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetFinishMode)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                            {
                                if (guid3 == 0x00002800)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetMemLimit)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00002900)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressReadUnusedFromInBuf)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00003500)
                            {
                                if (guid3 == 0x00003100)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetInStream)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00003400)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetOutStreamSize)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                            {
                                if (guid3 == 0x00003500)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetBufSize)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00004000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressFilter)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                    }
                }
                else
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
#elif defined(_ARCHITECTURE_BIG_ENDIAN)
                if (guid0 != 0x690f1723)
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                if (guid1 != 0xc1408a27)
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                if (guid2 == 0x00000003)
                {
                    if (guid3 != 0x00010000)
                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                {
                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ISequentialInStream)))
                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                }
                }
                else if (guid2 == 0x00000004)
                {
                    if (guid3 < 0x00250000)
                    {
                        if (guid3 < 0x00200000)
                        {
                            if (guid3 < 0x00180000)
                            {
                                if (guid3 != 0x00050000)
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            }
                            else
                            {
                                if (guid3 == 0x00180000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder2)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x001f0000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderPropertiesOpt)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00230000)
                            {
                                if (guid3 == 0x00200000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderProperties)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00220000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetDecoderProperties2)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                            {
                                if (guid3 == 0x00230000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressWriteCoderProperties)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00240000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressGetInStreamProcessedSize)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                    }
                    else
                    {
                        if (guid3 < 0x00310000)
                        {
                            if (guid3 < 0x00280000)
                            {
                                if (guid3 == 0x00250000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderMt)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00260000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetFinishMode)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                            {
                                if (guid3 == 0x00280000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetMemLimit)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00290000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressReadUnusedFromInBuf)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                        else
                        {
                            if (guid3 < 0x00350000)
                            {
                                if (guid3 == 0x00310000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetInStream)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00340000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetOutStreamSize)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                            {
                                if (guid3 == 0x00350000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetBufSize)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else if (guid3 == 0x00400000)
                                {
                                    if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressFilter)))
                                        throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                                }
                                else
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                        }
                    }
                }
                else
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
#else
#error "Undefined macro '_ARCHITECTURE_xxx_ENDIAN'"
#endif
#elif defined(_ARCHITECTURE_NATIVE_INTEGER_64_BIT)
            UInt64 guid0 = ((const UInt64*)&interfaceId)[0];
            UInt64 guid1 = ((const UInt64*)&interfaceId)[1];
#if defined(_ARCHITECTURE_LITTLE_ENDIAN)
                if (guid0 != 0x278a40c123170f69)
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                if (guid1 < 0x250004000000)
                {
                    if (guid1 < 0x200004000000)
                    {
                        if (guid1 < 0x180004000000)
                        {
                            if (guid1 == 0x10003000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ISequentialInStream)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x50004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x180004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder2)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x1f0004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderPropertiesOpt)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                    else
                    {
                        if (guid1 < 0x230004000000)
                        {
                            if (guid1 == 0x200004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderProperties)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x220004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetDecoderProperties2)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x230004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressWriteCoderProperties)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x240004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressGetInStreamProcessedSize)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                }
                else
                {
                    if (guid1 < 0x310004000000)
                    {
                        if (guid1 < 0x280004000000)
                        {
                            if (guid1 == 0x250004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderMt)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x260004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetFinishMode)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x280004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetMemLimit)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x290004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressReadUnusedFromInBuf)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                    else
                    {
                        if (guid1 < 0x350004000000)
                        {
                            if (guid1 == 0x310004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetInStream)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x340004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetOutStreamSize)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x350004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetBufSize)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400004000000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressFilter)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                }
#elif defined(_ARCHITECTURE_BIG_ENDIAN)
                if (guid0 != 0x690f1723c1408a27)
                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                if (guid1 < 0x400250000)
                {
                    if (guid1 < 0x400200000)
                    {
                        if (guid1 < 0x400180000)
                        {
                            if (guid1 == 0x300010000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ISequentialInStream)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400050000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x400180000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressCoder2)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x4001f0000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderPropertiesOpt)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                    else
                    {
                        if (guid1 < 0x400230000)
                        {
                            if (guid1 == 0x400200000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderProperties)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400220000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetDecoderProperties2)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x400230000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressWriteCoderProperties)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400240000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressGetInStreamProcessedSize)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                }
                else
                {
                    if (guid1 < 0x400310000)
                    {
                        if (guid1 < 0x400280000)
                        {
                            if (guid1 == 0x400250000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetCoderMt)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400260000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetFinishMode)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x400280000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetMemLimit)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400290000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressReadUnusedFromInBuf)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                    else
                    {
                        if (guid1 < 0x400350000)
                        {
                            if (guid1 == 0x400310000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetInStream)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400340000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetOutStreamSize)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                        else
                        {
                            if (guid1 == 0x400350000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressSetBufSize)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else if (guid1 == 0x400400000)
                            {
                                if (!IsEqualInterfaceId(interfaceId, __UUIDOF(ICompressFilter)))
                                    throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                            }
                            else
                                throw gcnew System::Exception("There is an error in the algorithm of 'SevenZip::Compression :: Implementation :: CreateManagedInterfaceObject()'.");
                        }
                    }
                }
#else
#error "Undefined macro '_ARCHITECTURE_xxx_ENDIAN'"
#endif
#else
#error "Undefined macro '_ARCHITECTURE_NATIVE_INTEGER_xx_BIT'"
#endif
        }

        void ValidateInterfaceIds()
        {
                ValidateInterfaceId(__UUIDOF(ISequentialInStream));
                ValidateInterfaceId(__UUIDOF(ICompressCoder));
                ValidateInterfaceId(__UUIDOF(ICompressCoder2));
                ValidateInterfaceId(__UUIDOF(ICompressSetCoderPropertiesOpt));
                ValidateInterfaceId(__UUIDOF(ICompressSetCoderProperties));
                ValidateInterfaceId(__UUIDOF(ICompressSetDecoderProperties2));
                ValidateInterfaceId(__UUIDOF(ICompressWriteCoderProperties));
                ValidateInterfaceId(__UUIDOF(ICompressGetInStreamProcessedSize));
                ValidateInterfaceId(__UUIDOF(ICompressSetCoderMt));
                ValidateInterfaceId(__UUIDOF(ICompressSetFinishMode));
                ValidateInterfaceId(__UUIDOF(ICompressSetMemLimit));
                ValidateInterfaceId(__UUIDOF(ICompressReadUnusedFromInBuf));
                ValidateInterfaceId(__UUIDOF(ICompressSetInStream));
                ValidateInterfaceId(__UUIDOF(ICompressSetOutStreamSize));
                ValidateInterfaceId(__UUIDOF(ICompressSetBufSize));
                ValidateInterfaceId(__UUIDOF(ICompressFilter));
        }
#endif
    }
}
