// This file is automatically generated. Do not rewrite manually.

#pragma once

#include "Platform.h"

#define IIDS_ISequentialInStream "{23170f69-40c1-278a-0000-000300010000}"
#define IIDS_ISequentialOutStream "{23170f69-40c1-278a-0000-000300020000}"
#define IIDS_IInStream "{23170f69-40c1-278a-0000-000300030000}"
#define IIDS_IOutStream "{23170f69-40c1-278a-0000-000300040000}"
#define IIDS_IStreamGetSize "{23170f69-40c1-278a-0000-000300060000}"
#define IIDS_IOutStreamFinish "{23170f69-40c1-278a-0000-000300070000}"
#define IIDS_IStreamGetProps "{23170f69-40c1-278a-0000-000300080000}"
#define IIDS_IStreamGetProps2 "{23170f69-40c1-278a-0000-000300090000}"
#define IIDS_ICompressProgressInfo "{23170f69-40c1-278a-0000-000400040000}"
#define IIDS_ICompressCoder "{23170f69-40c1-278a-0000-000400050000}"
#define IIDS_ICompressCoder2 "{23170f69-40c1-278a-0000-000400180000}"
#define IIDS_ICompressSetCoderPropertiesOpt "{23170f69-40c1-278a-0000-0004001f0000}"
#define IIDS_ICompressSetCoderProperties "{23170f69-40c1-278a-0000-000400200000}"
#define IIDS_ICompressSetDecoderProperties2 "{23170f69-40c1-278a-0000-000400220000}"
#define IIDS_ICompressWriteCoderProperties "{23170f69-40c1-278a-0000-000400230000}"
#define IIDS_ICompressGetInStreamProcessedSize "{23170f69-40c1-278a-0000-000400240000}"
#define IIDS_ICompressSetCoderMt "{23170f69-40c1-278a-0000-000400250000}"
#define IIDS_ICompressSetFinishMode "{23170f69-40c1-278a-0000-000400260000}"
#define IIDS_ICompressGetInStreamProcessedSize2 "{23170f69-40c1-278a-0000-000400270000}"
#define IIDS_ICompressSetMemLimit "{23170f69-40c1-278a-0000-000400280000}"
#define IIDS_ICompressReadUnusedFromInBuf "{23170f69-40c1-278a-0000-000400290000}"
#define IIDS_ICompressGetSubStreamSize "{23170f69-40c1-278a-0000-000400300000}"
#define IIDS_ICompressSetInStream "{23170f69-40c1-278a-0000-000400310000}"
#define IIDS_ICompressSetOutStream "{23170f69-40c1-278a-0000-000400320000}"
#define IIDS_ICompressSetOutStreamSize "{23170f69-40c1-278a-0000-000400340000}"
#define IIDS_ICompressSetBufSize "{23170f69-40c1-278a-0000-000400350000}"
#define IIDS_ICompressInitEncoder "{23170f69-40c1-278a-0000-000400360000}"
#define IIDS_ICompressSetInStream2 "{23170f69-40c1-278a-0000-000400370000}"
#define IIDS_ICompressFilter "{23170f69-40c1-278a-0000-000400400000}"
#define IIDS_ICompressCodecsInfo "{23170f69-40c1-278a-0000-000400600000}"
#define IIDS_ISetCompressCodecsInfo "{23170f69-40c1-278a-0000-000400610000}"
#define IIDS_ICryptoProperties "{23170f69-40c1-278a-0000-000400800000}"
#define IIDS_ICryptoResetInitVector "{23170f69-40c1-278a-0000-0004008c0000}"
#define IIDS_ICryptoSetPassword "{23170f69-40c1-278a-0000-000400900000}"
#define IIDS_ICryptoSetCRC "{23170f69-40c1-278a-0000-000400a00000}"
#define IIDS_IHasher "{23170f69-40c1-278a-0000-000400c00000}"
#define IIDS_IHashers "{23170f69-40c1-278a-0000-000400c10000}"

namespace SevenZip
{
    namespace NativeWrapper
    {
        SevenZip::NativeInterface::IUnknown^ CreateManagedInterfaceObject(const GUID& interfaceId, IUnknown* interfaceObject);
#ifdef _DEBUG
        void ValidateInterfaceIds();
#endif
    }
}
