// This file is automatically generated. Do not rewrite manually.

using System;
using System.Runtime.InteropServices;

namespace SevenZip.NativeWrapper.Managed.Platform
{
    partial class UnmanagedEntryPoint
    {
        /// <summary>
        /// IUnknown.QueryInterface
        /// </summary>
        /// <param name="ifp">IUnknown*</param>
        /// <param name="piid">ref NativeGUID</param>
        /// <param name="pvObject">out IntPtr</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IUnknown__QueryInterface")]
        public static extern HRESULT IUnknown__QueryInterface(IntPtr ifp, ref NativeGUID piid, out IntPtr pvObject);

        /// <summary>
        /// IUnknown.AddRef
        /// </summary>
        /// <param name="ifp">IUnknown*</param>
        /// <returns>UInt32</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IUnknown__AddRef")]
        public static extern UInt32 IUnknown__AddRef(IntPtr ifp);

        /// <summary>
        /// IUnknown.Release
        /// </summary>
        /// <param name="ifp">IUnknown*</param>
        /// <returns>UInt32</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IUnknown__Release")]
        public static extern UInt32 IUnknown__Release(IntPtr ifp);

        /// <summary>
        /// ISequentialInStream.Read
        /// </summary>
        /// <param name="ifp">ISequentialInStream*</param>
        /// <param name="data">void*</param>
        /// <param name="size">UInt32</param>
        /// <param name="processedSize">out UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ISequentialInStream__Read")]
        private static unsafe extern HRESULT ISequentialInStream__Read(IntPtr ifp, void* data, UInt32 size, out UInt32 processedSize);

        /// <summary>
        /// ISequentialOutStream.Write
        /// </summary>
        /// <param name="ifp">ISequentialOutStream*</param>
        /// <param name="data">void*</param>
        /// <param name="size">UInt32</param>
        /// <param name="processedSize">out UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ISequentialOutStream__Write")]
        private static unsafe extern HRESULT ISequentialOutStream__Write(IntPtr ifp, void* data, UInt32 size, out UInt32 processedSize);

#if false // IInStream interface is not supported by the wrapper.
        /// <summary>
        /// IInStream.Seek
        /// </summary>
        /// <param name="ifp">IInStream*</param>
        /// <param name="offset">Int64</param>
        /// <param name="seekOrigin">UInt32</param>
        /// <param name="newPosition">out UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IInStream__Seek")]
        public static extern HRESULT IInStream__Seek(IntPtr ifp, Int64 offset, UInt32 seekOrigin, out UInt64 newPosition);

#endif // IInStream interface is not supported by the wrapper.
#if false // IOutStream interface is not supported by the wrapper.
        /// <summary>
        /// IOutStream.Seek
        /// </summary>
        /// <param name="ifp">IOutStream*</param>
        /// <param name="offset">Int64</param>
        /// <param name="seekOrigin">UInt32</param>
        /// <param name="newPosition">out UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IOutStream__Seek")]
        public static extern HRESULT IOutStream__Seek(IntPtr ifp, Int64 offset, UInt32 seekOrigin, out UInt64 newPosition);

        /// <summary>
        /// IOutStream.SetSize
        /// </summary>
        /// <param name="ifp">IOutStream*</param>
        /// <param name="newSize">UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IOutStream__SetSize")]
        public static extern HRESULT IOutStream__SetSize(IntPtr ifp, UInt64 newSize);

#endif // IOutStream interface is not supported by the wrapper.
#if false // IStreamGetSize interface is not supported by the wrapper.
        /// <summary>
        /// IStreamGetSize.GetSize
        /// </summary>
        /// <param name="ifp">IStreamGetSize*</param>
        /// <param name="size">out UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IStreamGetSize__GetSize")]
        public static extern HRESULT IStreamGetSize__GetSize(IntPtr ifp, out UInt64 size);

#endif // IStreamGetSize interface is not supported by the wrapper.
#if false // IOutStreamFinish interface is not supported by the wrapper.
        /// <summary>
        /// IOutStreamFinish.OutStreamFinish
        /// </summary>
        /// <param name="ifp">IOutStreamFinish*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IOutStreamFinish__OutStreamFinish")]
        public static extern HRESULT IOutStreamFinish__OutStreamFinish(IntPtr ifp);

#endif // IOutStreamFinish interface is not supported by the wrapper.
#if false // IStreamGetProps interface is not supported by the wrapper.
        /// <summary>
        /// IStreamGetProps.GetProps
        /// </summary>
        /// <param name="ifp">IStreamGetProps*</param>
        /// <param name="size">UInt64*</param>
        /// <param name="cTime">void*</param>
        /// <param name="aTime">void*</param>
        /// <param name="mTime">void*</param>
        /// <param name="attrib">UInt32*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IStreamGetProps__GetProps")]
        private static unsafe extern HRESULT IStreamGetProps__GetProps(IntPtr ifp, UInt64* size, void* cTime, void* aTime, void* mTime, UInt32* attrib);

#endif // IStreamGetProps interface is not supported by the wrapper.
#if false // IStreamGetProps2 interface is not supported by the wrapper.
        /// <summary>
        /// IStreamGetProps2.GetProps2
        /// </summary>
        /// <param name="ifp">IStreamGetProps2*</param>
        /// <param name="props">void*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IStreamGetProps2__GetProps2")]
        private static unsafe extern HRESULT IStreamGetProps2__GetProps2(IntPtr ifp, void* props);

#endif // IStreamGetProps2 interface is not supported by the wrapper.
        /// <summary>
        /// ICompressProgressInfo.SetRatioInfo
        /// </summary>
        /// <param name="ifp">ICompressProgressInfo*</param>
        /// <param name="inSize">UInt64*</param>
        /// <param name="outSize">UInt64*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressProgressInfo__SetRatioInfo")]
        private static unsafe extern HRESULT ICompressProgressInfo__SetRatioInfo(IntPtr ifp, UInt64* inSize, UInt64* outSize);

        /// <summary>
        /// ICompressCoder.Code
        /// </summary>
        /// <param name="ifp">ICompressCoder*</param>
        /// <param name="inStreamReader">NativeInStreamReader</param>
        /// <param name="outStreamWriter">NativeOutStraamWriter</param>
        /// <param name="inSize">UInt64*</param>
        /// <param name="outSize">UInt64*</param>
        /// <param name="progressReporter">NativeProgressReporter?</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressCoder__Code")]
        private static unsafe extern HRESULT ICompressCoder__Code(IntPtr ifp, NativeInStreamReader inStreamReader, NativeOutStraamWriter outStreamWriter, UInt64* inSize, UInt64* outSize, NativeProgressReporter? progressReporter);

#if false // ICompressCoder2 interface is not supported by the wrapper.
        /// <summary>
        /// ICompressCoder2.Code
        /// </summary>
        /// <param name="ifp">ICompressCoder2*</param>
        /// <param name="inStreamReaders">NativeInStreamReader*</param>
        /// <param name="inSizes">UInt64**</param>
        /// <param name="numInStreams">UInt32</param>
        /// <param name="outStreamWriters">NativeOutStraamWriter*</param>
        /// <param name="outSizes">UInt64**</param>
        /// <param name="numOutStreams">UInt32</param>
        /// <param name="progressReporter">NativeProgressReporter?</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressCoder2__Code")]
        private static unsafe extern HRESULT ICompressCoder2__Code(IntPtr ifp, NativeInStreamReader* inStreamReaders, UInt64** inSizes, UInt32 numInStreams, NativeOutStraamWriter* outStreamWriters, UInt64** outSizes, UInt32 numOutStreams, NativeProgressReporter? progressReporter);

#endif // ICompressCoder2 interface is not supported by the wrapper.
        /// <summary>
        /// ICompressSetCoderPropertiesOpt.SetCoderPropertiesOpt
        /// </summary>
        /// <param name="ifp">ICompressSetCoderPropertiesOpt*</param>
        /// <param name="propIDs">CoderPropID*</param>
        /// <param name="props">PROPVARIANT*</param>
        /// <param name="numProps">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetCoderPropertiesOpt__SetCoderPropertiesOpt")]
        private static unsafe extern HRESULT ICompressSetCoderPropertiesOpt__SetCoderPropertiesOpt(IntPtr ifp, CoderPropID* propIDs, PROPVARIANT* props, UInt32 numProps);

        /// <summary>
        /// ICompressSetCoderProperties.SetCoderProperties
        /// </summary>
        /// <param name="ifp">ICompressSetCoderProperties*</param>
        /// <param name="propIDs">CoderPropID*</param>
        /// <param name="props">PROPVARIANT*</param>
        /// <param name="numProps">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetCoderProperties__SetCoderProperties")]
        private static unsafe extern HRESULT ICompressSetCoderProperties__SetCoderProperties(IntPtr ifp, CoderPropID* propIDs, PROPVARIANT* props, UInt32 numProps);

        /// <summary>
        /// ICompressSetDecoderProperties2.SetDecoderProperties2
        /// </summary>
        /// <param name="ifp">ICompressSetDecoderProperties2*</param>
        /// <param name="data">Byte*</param>
        /// <param name="size">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetDecoderProperties2__SetDecoderProperties2")]
        private static unsafe extern HRESULT ICompressSetDecoderProperties2__SetDecoderProperties2(IntPtr ifp, Byte* data, UInt32 size);

        /// <summary>
        /// ICompressWriteCoderProperties.WriteCoderProperties
        /// </summary>
        /// <param name="ifp">ICompressWriteCoderProperties*</param>
        /// <param name="outStreamWriter">NativeOutStraamWriter</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressWriteCoderProperties__WriteCoderProperties")]
        public static extern HRESULT ICompressWriteCoderProperties__WriteCoderProperties(IntPtr ifp, NativeOutStraamWriter outStreamWriter);

        /// <summary>
        /// ICompressGetInStreamProcessedSize.GetInStreamProcessedSize
        /// </summary>
        /// <param name="ifp">ICompressGetInStreamProcessedSize*</param>
        /// <param name="value">out UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressGetInStreamProcessedSize__GetInStreamProcessedSize")]
        public static extern HRESULT ICompressGetInStreamProcessedSize__GetInStreamProcessedSize(IntPtr ifp, out UInt64 value);

        /// <summary>
        /// ICompressSetCoderMt.SetNumberOfThreads
        /// </summary>
        /// <param name="ifp">ICompressSetCoderMt*</param>
        /// <param name="numThreads">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetCoderMt__SetNumberOfThreads")]
        public static extern HRESULT ICompressSetCoderMt__SetNumberOfThreads(IntPtr ifp, UInt32 numThreads);

        /// <summary>
        /// ICompressSetFinishMode.SetFinishMode
        /// </summary>
        /// <param name="ifp">ICompressSetFinishMode*</param>
        /// <param name="finishMode">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetFinishMode__SetFinishMode")]
        public static extern HRESULT ICompressSetFinishMode__SetFinishMode(IntPtr ifp, UInt32 finishMode);

#if false // ICompressGetInStreamProcessedSize2 interface is not supported by the wrapper.
        /// <summary>
        /// ICompressGetInStreamProcessedSize2.GetInStreamProcessedSize2
        /// </summary>
        /// <param name="ifp">ICompressGetInStreamProcessedSize2*</param>
        /// <param name="streamIndex">UInt32</param>
        /// <param name="value">out UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressGetInStreamProcessedSize2__GetInStreamProcessedSize2")]
        public static extern HRESULT ICompressGetInStreamProcessedSize2__GetInStreamProcessedSize2(IntPtr ifp, UInt32 streamIndex, out UInt64 value);

#endif // ICompressGetInStreamProcessedSize2 interface is not supported by the wrapper.
        /// <summary>
        /// ICompressSetMemLimit.SetMemLimit
        /// </summary>
        /// <param name="ifp">ICompressSetMemLimit*</param>
        /// <param name="memUsage">UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetMemLimit__SetMemLimit")]
        public static extern HRESULT ICompressSetMemLimit__SetMemLimit(IntPtr ifp, UInt64 memUsage);

        /// <summary>
        /// ICompressReadUnusedFromInBuf.ReadUnusedFromInBuf
        /// </summary>
        /// <param name="ifp">ICompressReadUnusedFromInBuf*</param>
        /// <param name="data">void*</param>
        /// <param name="size">UInt32</param>
        /// <param name="processedSize">out UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressReadUnusedFromInBuf__ReadUnusedFromInBuf")]
        private static unsafe extern HRESULT ICompressReadUnusedFromInBuf__ReadUnusedFromInBuf(IntPtr ifp, void* data, UInt32 size, out UInt32 processedSize);

#if false // ICompressGetSubStreamSize interface is not supported by the wrapper.
        /// <summary>
        /// ICompressGetSubStreamSize.GetSubStreamSize
        /// </summary>
        /// <param name="ifp">ICompressGetSubStreamSize*</param>
        /// <param name="subStream">UInt64</param>
        /// <param name="value">out UInt64</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressGetSubStreamSize__GetSubStreamSize")]
        public static extern HRESULT ICompressGetSubStreamSize__GetSubStreamSize(IntPtr ifp, UInt64 subStream, out UInt64 value);

#endif // ICompressGetSubStreamSize interface is not supported by the wrapper.
        /// <summary>
        /// ICompressSetInStream.SetInStream
        /// </summary>
        /// <param name="ifp">ICompressSetInStream*</param>
        /// <param name="inStreamReader">NativeInStreamReader</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetInStream__SetInStream")]
        public static extern HRESULT ICompressSetInStream__SetInStream(IntPtr ifp, NativeInStreamReader inStreamReader);

        /// <summary>
        /// ICompressSetInStream.ReleaseInStream
        /// </summary>
        /// <param name="ifp">ICompressSetInStream*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetInStream__ReleaseInStream")]
        public static extern HRESULT ICompressSetInStream__ReleaseInStream(IntPtr ifp);

#if false // ICompressSetOutStream interface is not supported by the wrapper.
        /// <summary>
        /// ICompressSetOutStream.SetOutStream
        /// </summary>
        /// <param name="ifp">ICompressSetOutStream*</param>
        /// <param name="outStreamWriter">NativeOutStraamWriter</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetOutStream__SetOutStream")]
        public static extern HRESULT ICompressSetOutStream__SetOutStream(IntPtr ifp, NativeOutStraamWriter outStreamWriter);

        /// <summary>
        /// ICompressSetOutStream.ReleaseOutStream
        /// </summary>
        /// <param name="ifp">ICompressSetOutStream*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetOutStream__ReleaseOutStream")]
        public static extern HRESULT ICompressSetOutStream__ReleaseOutStream(IntPtr ifp);

#endif // ICompressSetOutStream interface is not supported by the wrapper.
        /// <summary>
        /// ICompressSetOutStreamSize.SetOutStreamSize
        /// </summary>
        /// <param name="ifp">ICompressSetOutStreamSize*</param>
        /// <param name="outSize">UInt64*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetOutStreamSize__SetOutStreamSize")]
        private static unsafe extern HRESULT ICompressSetOutStreamSize__SetOutStreamSize(IntPtr ifp, UInt64* outSize);

        /// <summary>
        /// ICompressSetBufSize.SetInBufSize
        /// </summary>
        /// <param name="ifp">ICompressSetBufSize*</param>
        /// <param name="streamIndex">UInt32</param>
        /// <param name="size">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetBufSize__SetInBufSize")]
        public static extern HRESULT ICompressSetBufSize__SetInBufSize(IntPtr ifp, UInt32 streamIndex, UInt32 size);

        /// <summary>
        /// ICompressSetBufSize.SetOutBufSize
        /// </summary>
        /// <param name="ifp">ICompressSetBufSize*</param>
        /// <param name="streamIndex">UInt32</param>
        /// <param name="size">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetBufSize__SetOutBufSize")]
        public static extern HRESULT ICompressSetBufSize__SetOutBufSize(IntPtr ifp, UInt32 streamIndex, UInt32 size);

#if false // ICompressInitEncoder interface is not supported by the wrapper.
        /// <summary>
        /// ICompressInitEncoder.InitEncoder
        /// </summary>
        /// <param name="ifp">ICompressInitEncoder*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressInitEncoder__InitEncoder")]
        public static extern HRESULT ICompressInitEncoder__InitEncoder(IntPtr ifp);

#endif // ICompressInitEncoder interface is not supported by the wrapper.
#if false // ICompressSetInStream2 interface is not supported by the wrapper.
        /// <summary>
        /// ICompressSetInStream2.SetInStream2
        /// </summary>
        /// <param name="ifp">ICompressSetInStream2*</param>
        /// <param name="streamIndex">UInt32</param>
        /// <param name="inStreamReader">NativeInStreamReader</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetInStream2__SetInStream2")]
        public static extern HRESULT ICompressSetInStream2__SetInStream2(IntPtr ifp, UInt32 streamIndex, NativeInStreamReader inStreamReader);

        /// <summary>
        /// ICompressSetInStream2.ReleaseInStream2
        /// </summary>
        /// <param name="ifp">ICompressSetInStream2*</param>
        /// <param name="streamIndex">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressSetInStream2__ReleaseInStream2")]
        public static extern HRESULT ICompressSetInStream2__ReleaseInStream2(IntPtr ifp, UInt32 streamIndex);

#endif // ICompressSetInStream2 interface is not supported by the wrapper.
#if false // ICompressFilter interface is not supported by the wrapper.
        /// <summary>
        /// ICompressFilter.Init
        /// </summary>
        /// <param name="ifp">ICompressFilter*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressFilter__Init")]
        public static extern HRESULT ICompressFilter__Init(IntPtr ifp);

        /// <summary>
        /// ICompressFilter.Filter
        /// </summary>
        /// <param name="ifp">ICompressFilter*</param>
        /// <param name="data">Byte*</param>
        /// <param name="size">UInt32</param>
        /// <returns>UInt32</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressFilter__Filter")]
        private static unsafe extern UInt32 ICompressFilter__Filter(IntPtr ifp, Byte* data, UInt32 size);

#endif // ICompressFilter interface is not supported by the wrapper.
        /// <summary>
        /// ICompressCodecsInfo.GetNumMethods
        /// </summary>
        /// <param name="ifp">ICompressCodecsInfo*</param>
        /// <param name="numMethods">out UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressCodecsInfo__GetNumMethods")]
        public static extern HRESULT ICompressCodecsInfo__GetNumMethods(IntPtr ifp, out UInt32 numMethods);

        /// <summary>
        /// ICompressCodecsInfo.GetProperty
        /// </summary>
        /// <param name="ifp">ICompressCodecsInfo*</param>
        /// <param name="index">UInt32</param>
        /// <param name="propID">MethodPropID</param>
        /// <param name="value">ref PROPVARIANT</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressCodecsInfo__GetProperty")]
        public static extern HRESULT ICompressCodecsInfo__GetProperty(IntPtr ifp, UInt32 index, MethodPropID propID, ref PROPVARIANT value);

        /// <summary>
        /// ICompressCodecsInfo.CreateDecoder
        /// </summary>
        /// <param name="ifp">ICompressCodecsInfo*</param>
        /// <param name="index">UInt32</param>
        /// <param name="iid">ref NativeGUID</param>
        /// <param name="coder">out IntPtr</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressCodecsInfo__CreateDecoder")]
        public static extern HRESULT ICompressCodecsInfo__CreateDecoder(IntPtr ifp, UInt32 index, ref NativeGUID iid, out IntPtr coder);

        /// <summary>
        /// ICompressCodecsInfo.CreateEncoder
        /// </summary>
        /// <param name="ifp">ICompressCodecsInfo*</param>
        /// <param name="index">UInt32</param>
        /// <param name="iid">ref NativeGUID</param>
        /// <param name="coder">out IntPtr</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICompressCodecsInfo__CreateEncoder")]
        public static extern HRESULT ICompressCodecsInfo__CreateEncoder(IntPtr ifp, UInt32 index, ref NativeGUID iid, out IntPtr coder);

#if false // ISetCompressCodecsInfo interface is not supported by the wrapper.
        /// <summary>
        /// ISetCompressCodecsInfo.SetCompressCodecsInfo
        /// </summary>
        /// <param name="ifp">ISetCompressCodecsInfo*</param>
        /// <param name="compressCodecsInfo">void*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ISetCompressCodecsInfo__SetCompressCodecsInfo")]
        private static unsafe extern HRESULT ISetCompressCodecsInfo__SetCompressCodecsInfo(IntPtr ifp, void* compressCodecsInfo);

#endif // ISetCompressCodecsInfo interface is not supported by the wrapper.
#if false // ICryptoProperties interface is not supported by the wrapper.
        /// <summary>
        /// ICryptoProperties.SetKey
        /// </summary>
        /// <param name="ifp">ICryptoProperties*</param>
        /// <param name="data">Byte*</param>
        /// <param name="size">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICryptoProperties__SetKey")]
        private static unsafe extern HRESULT ICryptoProperties__SetKey(IntPtr ifp, Byte* data, UInt32 size);

        /// <summary>
        /// ICryptoProperties.SetInitVector
        /// </summary>
        /// <param name="ifp">ICryptoProperties*</param>
        /// <param name="data">Byte*</param>
        /// <param name="size">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICryptoProperties__SetInitVector")]
        private static unsafe extern HRESULT ICryptoProperties__SetInitVector(IntPtr ifp, Byte* data, UInt32 size);

#endif // ICryptoProperties interface is not supported by the wrapper.
#if false // ICryptoResetInitVector interface is not supported by the wrapper.
        /// <summary>
        /// ICryptoResetInitVector.ResetInitVector
        /// </summary>
        /// <param name="ifp">ICryptoResetInitVector*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICryptoResetInitVector__ResetInitVector")]
        public static extern HRESULT ICryptoResetInitVector__ResetInitVector(IntPtr ifp);

#endif // ICryptoResetInitVector interface is not supported by the wrapper.
#if false // ICryptoSetPassword interface is not supported by the wrapper.
        /// <summary>
        /// ICryptoSetPassword.CryptoSetPassword
        /// </summary>
        /// <param name="ifp">ICryptoSetPassword*</param>
        /// <param name="data">Byte*</param>
        /// <param name="size">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICryptoSetPassword__CryptoSetPassword")]
        private static unsafe extern HRESULT ICryptoSetPassword__CryptoSetPassword(IntPtr ifp, Byte* data, UInt32 size);

#endif // ICryptoSetPassword interface is not supported by the wrapper.
#if false // ICryptoSetCRC interface is not supported by the wrapper.
        /// <summary>
        /// ICryptoSetCRC.CryptoSetCRC
        /// </summary>
        /// <param name="ifp">ICryptoSetCRC*</param>
        /// <param name="crc">UInt32</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_ICryptoSetCRC__CryptoSetCRC")]
        public static extern HRESULT ICryptoSetCRC__CryptoSetCRC(IntPtr ifp, UInt32 crc);

#endif // ICryptoSetCRC interface is not supported by the wrapper.
#if false // IHasher interface is not supported by the wrapper.
        /// <summary>
        /// IHasher.Init
        /// </summary>
        /// <param name="ifp">IHasher*</param>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IHasher__Init")]
        public static extern void IHasher__Init(IntPtr ifp);

        /// <summary>
        /// IHasher.Update
        /// </summary>
        /// <param name="ifp">IHasher*</param>
        /// <param name="data">void*</param>
        /// <param name="size">UInt32</param>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IHasher__Update")]
        private static unsafe extern void IHasher__Update(IntPtr ifp, void* data, UInt32 size);

        /// <summary>
        /// IHasher.Final
        /// </summary>
        /// <param name="ifp">IHasher*</param>
        /// <param name="digest">Byte*</param>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IHasher__Final")]
        private static unsafe extern void IHasher__Final(IntPtr ifp, Byte* digest);

        /// <summary>
        /// IHasher.GetDigestSize
        /// </summary>
        /// <param name="ifp">IHasher*</param>
        /// <returns>UInt32</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IHasher__GetDigestSize")]
        public static extern UInt32 IHasher__GetDigestSize(IntPtr ifp);

#endif // IHasher interface is not supported by the wrapper.
#if false // IHashers interface is not supported by the wrapper.
        /// <summary>
        /// IHashers.GetNumHashers
        /// </summary>
        /// <param name="ifp">IHashers*</param>
        /// <returns>UInt32</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IHashers__GetNumHashers")]
        public static extern UInt32 IHashers__GetNumHashers(IntPtr ifp);

        /// <summary>
        /// IHashers.GetHasherProp
        /// </summary>
        /// <param name="ifp">IHashers*</param>
        /// <param name="index">UInt32</param>
        /// <param name="propID">MethodPropID</param>
        /// <param name="value">PROPVARIANT*</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IHashers__GetHasherProp")]
        private static unsafe extern HRESULT IHashers__GetHasherProp(IntPtr ifp, UInt32 index, MethodPropID propID, PROPVARIANT* value);

        /// <summary>
        /// IHashers.CreateHasher
        /// </summary>
        /// <param name="ifp">IHashers*</param>
        /// <param name="index">UInt32</param>
        /// <param name="hasher">void**</param>
        /// <returns>HRESULT</returns>
        [DllImport("SevenZip.NativeWrapper.Unmanaged", EntryPoint = "EXPORTED_IHashers__CreateHasher")]
        private static unsafe extern HRESULT IHashers__CreateHasher(IntPtr ifp, UInt32 index, void** hasher);

#endif // IHashers interface is not supported by the wrapper.
    }
}
