// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface.Compression;
using SevenZip.NativeWrapper.Managed.win.x64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.win.x64.Compression
{
    class CompressSetFinishMode
        : Unknown, ICompressSetFinishMode
    {
        protected CompressSetFinishMode(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        public static ICompressSetFinishMode Create(IntPtr nativeInterfaceObject)
        {
            if (nativeInterfaceObject == IntPtr.Zero)
                throw new ArgumentNullException(nameof(nativeInterfaceObject));

            return new CompressSetFinishMode(nativeInterfaceObject);
        }

        void ICompressSetFinishMode.SetFinishMode(bool finishMode)
        {
            var result = UnmanagedEntryPoint.ICompressSetFinishMode__SetFinishMode(NativeInterfaceObject, finishMode ? 1U : 0U);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
        }
    }
}
