// This file is automatically generated. Do not rewrite manually.

using SevenZip.NativeInterface.Compression;
using SevenZip.NativeWrapper.Managed.linux.arm64.Platform;
using System;

namespace SevenZip.NativeWrapper.Managed.linux.arm64.Compression
{
    class CompressSetMemLimit
        : Unknown, ICompressSetMemLimit
    {
        protected CompressSetMemLimit(IntPtr nativeInterfaceObject)
            : base(nativeInterfaceObject)
        {
        }

        public static ICompressSetMemLimit Create(IntPtr nativeInterfaceObject)
        {
            return new CompressSetMemLimit(nativeInterfaceObject);
        }

        void ICompressSetMemLimit.SetMemLimit(UInt64 memUsage)
        {
            var result = UnmanagedEntryPoint.ICompressSetMemLimit__SetMemLimit(NativeInterfaceObject, memUsage);
            if (result != HRESULT.S_OK)
                throw result.GetExceptionFromHRESULT();
        }
    }
}
